//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksSample1.Models3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SamplDbEntities : DbContext
    {
        public SamplDbEntities()
            : base("name=SamplDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sample_table1> sample_table1 { get; set; }
        public virtual DbSet<SYS_USER> SYS_USER { get; set; }
        public virtual DbSet<table1> table1 { get; set; }
        public virtual DbSet<table2> table2 { get; set; }
        public virtual DbSet<table3> table3 { get; set; }
        public virtual DbSet<table4> table4 { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<src_file> src_file { get; set; }
    }
}
