using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
namespace AdventureWorks1.Models5
{
    [Table("dbo.DatabaseLog")]
    public partial class DatabaseLog
    {
        public DatabaseLog()
        {
            DatabaseLogId = 0;
            PostTime = DateTime.Parse("0001/01/01 0:00:00");
            DatabaseUser = null;
            Event = null;
            Schema = null;
            Object = null;
            Tsql = null;
            XmlEvent = null;

        }

        ///<summary>Primary key for DatabaseLog records.</summary>
        [Key]
        [Column("DatabaseLogID", Order = 0, TypeName = "int")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int DatabaseLogId { get; set; }

        ///<summary>The date and time the DDL change occurred.</summary>
        [Column("PostTime", Order = 1, TypeName = "datetime")]
        public DateTime PostTime { get; set; }

        ///<summary>The user who implemented the DDL change.</summary>
        [Required]
        [Column("DatabaseUser", Order = 2, TypeName = "nvarchar")]
        [StringLength(128)]
        public string DatabaseUser { get; set; }

        ///<summary>The type of DDL statement that was executed.</summary>
        [Required]
        [Column("Event", Order = 3, TypeName = "nvarchar")]
        [StringLength(128)]
        public string Event { get; set; }

        ///<summary>The schema to which the changed object belongs.</summary>
        [Column("Schema", Order = 4, TypeName = "nvarchar")]
        [StringLength(128)]
        public string Schema { get; set; }

        ///<summary>The object that was changed by the DDL statment.</summary>
        [Column("Object", Order = 5, TypeName = "nvarchar")]
        [StringLength(128)]
        public string Object { get; set; }

        ///<summary>The exact Transact-SQL statement that was executed.</summary>
        [Required]
        [Column("TSQL", Order = 6, TypeName = "nvarchar")]
        public string Tsql { get; set; }

        ///<summary>The raw XML data generated by database trigger.</summary>
        [Required]
        [Column("XmlEvent", Order = 7, TypeName = "xml")]
        public string XmlEvent { get; set; }

    }
}
