//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksSample1.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vJobCandidate
    {
        public int JobCandidateID { get; set; }
        public Nullable<int> BusinessEntityID { get; set; }
        public string Name_Prefix { get; set; }
        public string Name_First { get; set; }
        public string Name_Middle { get; set; }
        public string Name_Last { get; set; }
        public string Name_Suffix { get; set; }
        public string Skills { get; set; }
        public string Addr_Type { get; set; }
        public string Addr_Loc_CountryRegion { get; set; }
        public string Addr_Loc_State { get; set; }
        public string Addr_Loc_City { get; set; }
        public string Addr_PostalCode { get; set; }
        public string EMail { get; set; }
        public string WebSite { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
