//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksSample1.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vJobCandidateEmployment
    {
        public int JobCandidateID { get; set; }
        public Nullable<System.DateTime> Emp_StartDate { get; set; }
        public Nullable<System.DateTime> Emp_EndDate { get; set; }
        public string Emp_OrgName { get; set; }
        public string Emp_JobTitle { get; set; }
        public string Emp_Responsibility { get; set; }
        public string Emp_FunctionCategory { get; set; }
        public string Emp_IndustryCategory { get; set; }
        public string Emp_Loc_CountryRegion { get; set; }
        public string Emp_Loc_State { get; set; }
        public string Emp_Loc_City { get; set; }
    }
}
