//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksSample1.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductModelCatalogDescription
    {
        public int ProductModelID { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Manufacturer { get; set; }
        public string Copyright { get; set; }
        public string ProductURL { get; set; }
        public string WarrantyPeriod { get; set; }
        public string WarrantyDescription { get; set; }
        public string NoOfYears { get; set; }
        public string MaintenanceDescription { get; set; }
        public string Wheel { get; set; }
        public string Saddle { get; set; }
        public string Pedal { get; set; }
        public string BikeFrame { get; set; }
        public string Crankset { get; set; }
        public string PictureAngle { get; set; }
        public string PictureSize { get; set; }
        public string ProductPhotoID { get; set; }
        public string Material { get; set; }
        public string Color { get; set; }
        public string ProductLine { get; set; }
        public string Style { get; set; }
        public string RiderExperience { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
