using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace AdventureWorksCore.Models
{
    [Table("DatabaseLog", Schema="dbo")]
    public partial class DatabaseLog
    {
        public DatabaseLog()
        {

        }

        ///<summary>Primary key for DatabaseLog records.</summary>
        ///<remarks></remarks>
        [Key]
        [Column("DatabaseLogID", Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int DatabaseLogId { get; set; }

        ///<summary>The date and time the DDL change occurred.</summary>
        ///<remarks></remarks>
        [Column("PostTime", Order = 1)]
        public DateTime PostTime { get; set; }

        ///<summary>The user who implemented the DDL change.</summary>
        ///<remarks></remarks>
        [Required]
        [Column("DatabaseUser", Order = 2)]
        [StringLength(128)]
        public string DatabaseUser { get; set; }

        ///<summary>The type of DDL statement that was executed.</summary>
        ///<remarks></remarks>
        [Required]
        [Column("Event", Order = 3)]
        [StringLength(128)]
        public string Event { get; set; }

        ///<summary>The schema to which the changed object belongs.</summary>
        ///<remarks></remarks>
        [Column("Schema", Order = 4)]
        [StringLength(128)]
        public string Schema { get; set; }

        ///<summary>The object that was changed by the DDL statment.</summary>
        ///<remarks></remarks>
        [Column("Object", Order = 5)]
        [StringLength(128)]
        public string Object { get; set; }

        ///<summary>The exact Transact-SQL statement that was executed.</summary>
        ///<remarks></remarks>
        [Required]
        [Column("TSQL", Order = 6)]
        public string Tsql { get; set; }

        ///<summary>The raw XML data generated by database trigger.</summary>
        ///<remarks></remarks>
        [Required]
        [Column("XmlEvent", Order = 7)]
        public string XmlEvent { get; set; }

    }
}
